steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Run unit tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

  # Step 3: Install Python dependencies
  - name: 'gcr.io/cloud-builders/python'
    args: ['pip', 'install', '-r', 'requirements.txt']

  # Step 4: Run the Flask application (assuming it listens on port 8080)
  - name: 'gcr.io/cloud-builders/python'
    args: ['app.py']
    env:
    - 'PORT=8080'
