steps:
  - name: 'gcr.io/cloud-builders/python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install -r requirements.txt'

  - name: 'gcr.io/cloud-builders/python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'python -m unittest discover -s tests'

options:
  logging: CLOUD_LOGGING_ONLY
