steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Run unit tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

options:
  logging: CLOUD_LOGGING_ONLY