steps:
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  - name: python
    entrypoint: 'bash'
    args:
      - '-c'
      - 'python -m unittest discover -s tests'

options:
  logging: CLOUD_LOGGING_ONLY
